baseurl = "http://paulcapestany.com/"
languageCode = "en-us"
title = "Paul Capestany"
theme = "hugo-uno"
canonifyurls = true
author = "Paul Capestany"

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Paul"
  github = "PaulCapestany"
  twitter = "PaulCapestany"
  facebook = "PaulCapestany"
  lastfm = "PaulCapestany"
  foursquare = "PaulCapestany"
  bitcoin = "PaulCapestany"
  youtube = "PaulCapestany"
  rss = "PaulCapestany"
  flickr = "pcapestany"
  email = "capestany@gmail.com"
  description = "Ex-neuroscience researcher turned techie startupper, recovering event organizer, vegan, self-taught programmer, gym rat, obsessive optimizer, enjoys good beer…"
  # cv = "/pages/cv"
  # muut = "fredrikloch"
  linkedin = "PaulCapestany"
  cover = "/images/background_photo.jpg"
  logo = "/images/paul_capestany.png"
