baseurl = "http://paulcapestany.com"
languageCode = "en-us"
title = "Paul Capestany"
theme = "material-design"
canonifyurls = true
author = "Paul Capestany"

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Paul"
  github = "PaulCapestany"
  twitter = "PaulCapestany"
  facebook = "PaulCapestany"
  lastfm = "PaulCapestany"
  foursquare = "PaulCapestany"
  bitcoin = "PaulCapestany"
  youtube = "PaulCapestany"
  rss = "PaulCapestany"
  flickr = "pcapestany"
  email = "capestany@gmail.com"
  description = "Ex-neuroscience researcher turned techie startupper, recovering event organizer, vegan, self-taught programmer, gym rat, obsessive optimizer, enjoys good beer…"
  linkedin = "PaulCapestany"
  # cover = "/images/background_photo.jpg"
  # logo = "/images/paul_capestany.png"
  headerCover = "images/background_photo.jpg" # optional
  footerCover = "images/footer.jpg" # optional

  MetaDataFormat = "toml"
  paginate = 9 # To specify a multiple of 3

  [permalinks]
    post = "/:year/:month/:day/:title/" # optional
